#!/bin/sh
# @author: CupIvan <mail@cupivan.ru>
# @date:   01.03.2016

FNAME=""
if [[ "$1" != "" ]]
then
	DIR=$1/`date +%Y-%m`
	mkdir -p $DIR 2>/dev/null
	FNAME=$DIR/`date +%Y-%m-%d`.raw
fi

# main loop
while read time idle title
do
	DAY=$((time/3600/24))
	if [[ "$START_DAY" ==   "" ]]; then START_DAY=$DAY; fi
	if [[ "$START_DAY" != $DAY ]]; then break; fi

	ST="$time\t$idle\t$title"
	if [[ "$FNAME" != "" ]]; then echo -e $ST >> $FNAME; else echo -e $ST; fi
done
