#!/usr/bin/php
<?php
/**
 * Simplre compressor for time logs
 * @author CupIvan <mail@cupivan.ru>
 * @date   01.03.2016
 */

$fname = @$_SERVER['argv'][1];
$fname = '../../logs/time/2016-03/2016-03-01.json';
$st = file_get_contents($fname);
$st = str_replace('t:"', 'T:"', $st);
$st = preg_replace('/(timestamp|t|T|i|h):/', '"$1":', $st);
$st = "[$st{}]";
$json = []; $current = ['h'=>-1]; $last = 0;
foreach (json_decode($st, true) as $a)
if (isset($a['h']))
{
	if ($current['h'] != $a['h'])
	{
		$current = $a;
		array_push($json, $a);
		$last = count($json) - 1;
		continue;
	}
	$json[$last]['dt'] = $a['t'] - $json[$last]['t'];
	$json[$last]['i']  = max($json[$last]['i'], $a['i']);
}

$json = json_encode($json, JSON_UNESCAPED_UNICODE);
$json = str_replace('},{', "},\n{", $json);
echo $json;
